In [66]:
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [67]:
import pandas as pd
import numpy as np
import keras

import warnings
warnings.simplefilter('ignore', FutureWarning)

In [68]:
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
concrete_data = pd.read_csv(filepath)

concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [69]:
concrete_data.shape

(1030, 9)

In [70]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [71]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [72]:
concrete_data_columns = concrete_data.columns

In [73]:
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [74]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [75]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [76]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [77]:
n_cols = predictors_norm.shape[1] # number of predictors

In [78]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

In [79]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='linear'))
    model.add(Dense(50, activation='linear'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [80]:
model = regression_model()

In [81]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.1, epochs=100, verbose=2)

Epoch 1/100
29/29 - 0s - 15ms/step - loss: 1558.7057 - val_loss: 1173.5341
Epoch 2/100
29/29 - 0s - 2ms/step - loss: 1444.0031 - val_loss: 1167.5731
Epoch 3/100
29/29 - 0s - 2ms/step - loss: 1241.9902 - val_loss: 1135.8733
Epoch 4/100
29/29 - 0s - 2ms/step - loss: 947.5002 - val_loss: 1012.3885
Epoch 5/100
29/29 - 0s - 2ms/step - loss: 628.4089 - val_loss: 644.7702
Epoch 6/100
29/29 - 0s - 2ms/step - loss: 324.2780 - val_loss: 239.2691
Epoch 7/100
29/29 - 0s - 2ms/step - loss: 152.7133 - val_loss: 81.3946
Epoch 8/100
29/29 - 0s - 2ms/step - loss: 118.5461 - val_loss: 72.6675
Epoch 9/100
29/29 - 0s - 2ms/step - loss: 116.1248 - val_loss: 70.9142
Epoch 10/100
29/29 - 0s - 2ms/step - loss: 115.5925 - val_loss: 69.9237
Epoch 11/100
29/29 - 0s - 2ms/step - loss: 115.1292 - val_loss: 73.1118
Epoch 12/100
29/29 - 0s - 2ms/step - loss: 114.5718 - val_loss: 69.6114
Epoch 13/100
29/29 - 0s - 2ms/step - loss: 114.8828 - val_loss: 62.6592
Epoch 14/100
29/29 - 0s - 2ms/step - loss: 115.5177 - val_loss: 76.6012
Epoch 15/100
29/29 - 0s - 2ms/step - loss: 114.4824 - val_loss: 69.0185
Epoch 16/100
29/29 - 0s - 2ms/step - loss: 114.7495 - val_loss: 72.3685
Epoch 17/100
29/29 - 0s - 2ms/step - loss: 114.2273 - val_loss: 65.4115
Epoch 18/100
29/29 - 0s - 2ms/step - loss: 114.1907 - val_loss: 65.8707
Epoch 19/100
29/29 - 0s - 2ms/step - loss: 114.2573 - val_loss: 64.5345
Epoch 20/100
29/29 - 0s - 2ms/step - loss: 115.5691 - val_loss: 70.8517
Epoch 21/100
29/29 - 0s - 2ms/step - loss: 114.7653 - val_loss: 71.4272
Epoch 22/100
29/29 - 0s - 2ms/step - loss: 114.1419 - val_loss: 68.1686
Epoch 23/100
29/29 - 0s - 2ms/step - loss: 114.7354 - val_loss: 69.1368
Epoch 24/100
29/29 - 0s - 2ms/step - loss: 114.0879 - val_loss: 66.1243
Epoch 25/100
29/29 - 0s - 2ms/step - loss: 114.9344 - val_loss: 66.4874
Epoch 26/100
29/29 - 0s - 2ms/step - loss: 114.0594 - val_loss: 65.9090
Epoch 27/100
29/29 - 0s - 2ms/step - loss: 113.9134 - val_loss: 68.0123
Epoch 28/100
29/29 - 0s - 2ms/step - loss: 114.0586 - val_loss: 60.0982
Epoch 29/100
29/29 - 0s - 2ms/step - loss: 114.0651 - val_loss: 63.2383
Epoch 30/100
29/29 - 0s - 2ms/step - loss: 114.4594 - val_loss: 63.7574
Epoch 31/100
29/29 - 0s - 2ms/step - loss: 114.1454 - val_loss: 66.8945
Epoch 32/100
29/29 - 0s - 2ms/step - loss: 114.9334 - val_loss: 66.5375
Epoch 33/100
29/29 - 0s - 2ms/step - loss: 115.4182 - val_loss: 61.2754
Epoch 34/100
29/29 - 0s - 2ms/step - loss: 115.4563 - val_loss: 64.7305
Epoch 35/100
29/29 - 0s - 2ms/step - loss: 114.1431 - val_loss: 62.3394
Epoch 36/100
29/29 - 0s - 2ms/step - loss: 115.0570 - val_loss: 62.8321
Epoch 37/100
29/29 - 0s - 2ms/step - loss: 114.6726 - val_loss: 62.0048
Epoch 38/100
29/29 - 0s - 2ms/step - loss: 114.4571 - val_loss: 59.6367
Epoch 39/100
29/29 - 0s - 2ms/step - loss: 114.6877 - val_loss: 63.4992
Epoch 40/100
29/29 - 0s - 2ms/step - loss: 115.8720 - val_loss: 62.7673
Epoch 41/100
29/29 - 0s - 2ms/step - loss: 114.3222 - val_loss: 63.6776
Epoch 42/100
29/29 - 0s - 2ms/step - loss: 114.2131 - val_loss: 63.1548
Epoch 43/100
29/29 - 0s - 2ms/step - loss: 114.7300 - val_loss: 69.4903
Epoch 44/100
29/29 - 0s - 2ms/step - loss: 113.9406 - val_loss: 61.8181
Epoch 45/100
29/29 - 0s - 2ms/step - loss: 113.6530 - val_loss: 66.7456
Epoch 46/100
29/29 - 0s - 2ms/step - loss: 114.1831 - val_loss: 62.9849
Epoch 47/100
29/29 - 0s - 2ms/step - loss: 115.2492 - val_loss: 65.9283
Epoch 48/100
29/29 - 0s - 2ms/step - loss: 114.1699 - val_loss: 65.6344
Epoch 49/100
29/29 - 0s - 2ms/step - loss: 113.7523 - val_loss: 70.0922
Epoch 50/100
29/29 - 0s - 2ms/step - loss: 114.4420 - val_loss: 63.8820
Epoch 51/100
29/29 - 0s - 2ms/step - loss: 114.5946 - val_loss: 62.3021
Epoch 52/100
29/29 - 0s - 2ms/step - loss: 114.1744 - val_loss: 60.4403
Epoch 53/100
29/29 - 0s - 2ms/step - loss: 114.4771 - val_loss: 62.4907
Epoch 54/100
29/29 - 0s - 2ms/step - loss: 113.9617 - val_loss: 65.1126
Epoch 55/100
29/29 - 0s - 2ms/step - loss: 114.1509 - val_loss: 66.7112
Epoch 56/100
29/29 - 0s - 2ms/step - loss: 114.4009 - val_loss: 67.4637
Epoch 57/100
29/29 - 0s - 3ms/step - loss: 115.1503 - val_loss: 67.5747
Epoch 58/100
29/29 - 0s - 2ms/step - loss: 113.8037 - val_loss: 60.9943
Epoch 59/100
29/29 - 0s - 2ms/step - loss: 113.7925 - val_loss: 68.0005
Epoch 60/100
29/29 - 0s - 2ms/step - loss: 114.2420 - val_loss: 64.0595
Epoch 61/100
29/29 - 0s - 2ms/step - loss: 114.2426 - val_loss: 63.1465
Epoch 62/100
29/29 - 0s - 2ms/step - loss: 113.7729 - val_loss: 64.4443
Epoch 63/100
29/29 - 0s - 2ms/step - loss: 113.7718 - val_loss: 63.1513
Epoch 64/100
29/29 - 0s - 2ms/step - loss: 114.5314 - val_loss: 64.1121
Epoch 65/100
29/29 - 0s - 2ms/step - loss: 115.0669 - val_loss: 65.9504
Epoch 66/100
29/29 - 0s - 2ms/step - loss: 114.6025 - val_loss: 65.6926
Epoch 67/100
29/29 - 0s - 2ms/step - loss: 114.9632 - val_loss: 61.6986
Epoch 68/100
29/29 - 0s - 2ms/step - loss: 114.0465 - val_loss: 62.2054
Epoch 69/100
29/29 - 0s - 2ms/step - loss: 114.0340 - val_loss: 62.6971
Epoch 70/100
29/29 - 0s - 2ms/step - loss: 114.3198 - val_loss: 66.4074
Epoch 71/100
29/29 - 0s - 2ms/step - loss: 114.2621 - val_loss: 64.6617
Epoch 72/100
29/29 - 0s - 2ms/step - loss: 113.9788 - val_loss: 68.8142
Epoch 73/100
29/29 - 0s - 2ms/step - loss: 114.6452 - val_loss: 57.4867
Epoch 74/100
29/29 - 0s - 2ms/step - loss: 113.7925 - val_loss: 68.7525
Epoch 75/100
29/29 - 0s - 2ms/step - loss: 114.6382 - val_loss: 64.0711
Epoch 76/100
29/29 - 0s - 2ms/step - loss: 114.3158 - val_loss: 67.6469
Epoch 77/100
29/29 - 0s - 2ms/step - loss: 114.8342 - val_loss: 70.2201
Epoch 78/100
29/29 - 0s - 2ms/step - loss: 114.9655 - val_loss: 66.0984
Epoch 79/100
29/29 - 0s - 2ms/step - loss: 114.1600 - val_loss: 65.9187
Epoch 80/100
29/29 - 0s - 2ms/step - loss: 114.5855 - val_loss: 62.8518
Epoch 81/100
29/29 - 0s - 2ms/step - loss: 114.1238 - val_loss: 60.5147
Epoch 82/100
29/29 - 0s - 2ms/step - loss: 114.4553 - val_loss: 65.7284
Epoch 83/100
29/29 - 0s - 2ms/step - loss: 113.6873 - val_loss: 59.1547
Epoch 84/100
29/29 - 0s - 2ms/step - loss: 113.4888 - val_loss: 65.5755
Epoch 85/100
29/29 - 0s - 2ms/step - loss: 113.9611 - val_loss: 64.6181
Epoch 86/100
29/29 - 0s - 2ms/step - loss: 113.9316 - val_loss: 62.3438
Epoch 87/100
29/29 - 0s - 2ms/step - loss: 114.4060 - val_loss: 60.4509
Epoch 88/100
29/29 - 0s - 2ms/step - loss: 113.9561 - val_loss: 63.9215
Epoch 89/100
29/29 - 0s - 2ms/step - loss: 114.2046 - val_loss: 60.3719
Epoch 90/100
29/29 - 0s - 2ms/step - loss: 114.8783 - val_loss: 68.6429
Epoch 91/100
29/29 - 0s - 2ms/step - loss: 114.1301 - val_loss: 62.4523
Epoch 92/100
29/29 - 0s - 2ms/step - loss: 114.0583 - val_loss: 68.6491
Epoch 93/100
29/29 - 0s - 2ms/step - loss: 114.1005 - val_loss: 62.2913
Epoch 94/100
29/29 - 0s - 2ms/step - loss: 114.3733 - val_loss: 66.3209
Epoch 95/100
29/29 - 0s - 2ms/step - loss: 115.5348 - val_loss: 60.2362
Epoch 96/100
29/29 - 0s - 2ms/step - loss: 114.4126 - val_loss: 66.2210
Epoch 97/100
29/29 - 0s - 2ms/step - loss: 113.7799 - val_loss: 59.7292
Epoch 98/100
29/29 - 0s - 2ms/step - loss: 114.4213 - val_loss: 68.4046
Epoch 99/100
29/29 - 0s - 2ms/step - loss: 113.8308 - val_loss: 60.3451
Epoch 100/100
29/29 - 0s - 2ms/step - loss: 113.7642 - val_loss: 65.3074